spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WarehouseDb;encrypt=false
spring.datasource.username=sa
spring.datasource.password=MyStrongPass123!

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

